services:
    db:
        image: mysql:8.0
        container_name: assessment
        restart: always
        ports:
            - "3307:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: assessment_db
            MYSQL_USER: user
            MYSQL_PASSWORD: password
      