# spring.application.name=diagnostic-test

spring:
  application:
    name: riwiTest
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/riwiTest
    password: Rlwl2023.
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: 'true'

server:
    port: 0 
    servlet:
      context-path: /api/v1/
